### PR TITLE
Documentation and example for Task and Motion Planning

### PR DESCRIPTION
**Pull request by uwe-koeckemann**
Filling out the documentation with entries for TAMP. The engine documentation seems to be pulled from the up-spiderplan git and I extended it there to be in line with, e.g., Tamer. 

- Added section to problem_representation.rst
- Added code snippet used in example

Let me know if anything is missing.

### CODE REVIEW

**Comment by arbimo** [comment]
Thanks @uwe-koeckemann 
There is a pending PR #517 that reorganize the documentation. I was awaiting it to be merge to then ping you to fill it in :/

The structure should be  for each planning class (e.g. TAMP): 
 - a short overview in `Problem Representation` (objective: discoverability)
 - A more detailed walk through for each problem class

In the short overview, should contain a descriptive text (yours is perfect), a "syntax overview" and a link to the detailed walk through.

To perfectly fit this schema, I think you could:

 1. convert your example to a notebook with some inline explanation of the specific concepts (occupancy map, motion model, ...) and have some example plan results
 2. Place a slightly shorter extract to serve as a syntax overview

Note that notebooks are automatically converted to HTML so you can link them directly. 

The PR also provide a candidate reorganization for the engines. We will need to include a section on TAMP engines, essentially linking to `up-spiderplan`.

**Comment by arbimo** [comment]
@uwe-koeckemann The corresponding PR has been merged. You could perhaps rebase your code to build on top of it.

**Comment by uwe-koeckemann** [comment]
@arbimo I think I re-based successfully on-top of master. I will look into the other points you mentioned asap. The notebook will be difficult because of the reliance on docker. I got pretty far re-doing my dockerfile with colab, but in the end it did not manage to connect to the spiderplan server.

**Comment by arbimo** [comment]
@uwe-koeckemann We need to finish this ASAP.  At the very least the modeling part should be completed.
If it not possible to add the the solver and demonstrate solving that is probably fine (even if suboptimal) as the primary responsibility of the UP is modeling and the solver is external to the repository. If that's the route you take, make sure that the instructions for installing the solver is well documented and reproducible on the solver side

**Comment by uwe-koeckemann** [comment]
@arbimo Just to be clear: with the modeling part you mean the Colab notebook that is then used to populate the docs page with a detailed usage example? And to add this I need to add the Colab link on the corresponding page?  I will try to fix this tomorrow.

**Comment by uwe-koeckemann** [comment]
@arbimo I added the TAMP notebook and updated the one in the up-spiderplan repo with instructions on how to run the notebook locally. I tried to add TAMP parts to all places that were missing it. Let me know if I missed something. I am available this afternoon or tomorrow all day for any other missing things or fixes.

**Comment by arbimo** [comment]
@uwe-koeckemann I did a substantially clean up and fixed a few problem in doc generation. Could you check that I did break anything and fix the last problems in CI ?

**Comment by uwe-koeckemann** [comment]
> @uwe-koeckemann I did a substantially clean up and fixed a few problem in doc generation. Could you check that I did break anything and fix the last problems in CI ?

Trying to fix the CI issues. Can we exclude the TAMP notebook from the Colab tests? It relies on a local file and would anyway not work since it relies on docker internally.

**Comment by arbimo** [comment]
> Trying to fix the CI issues. Can we exclude the TAMP notebook from the Colab tests? It relies on a local file and would anyway not work since it relies on docker internally.

Done ! There is a special tag that you can use to avoid running a particular cell in CI. I deactivated them for the two cells that required up_spiderplan (and added a disclaimer that it won't run in colab.

**Review by arbimo — APPROVED** [review]
Thanks a lot @uwe-koeckemann !

**Pull request merged**
