### PR TITLE
doc: Add showcase on behavior tree testing

### PR DESCRIPTION
**Pull request by arbimo**
- doc: add initial showcase draft for behavior tree testing
- doc: mainly cosmetic changes to showcase behavior-tree-testing

### CODE REVIEW

**Comment by arbimo** [comment]
@uwe-koeckemann @madmage Could you double check this? In particular, I believe the *problem encoder* part should be completed, but there are probably several minor improvements to be done.

**Comment by arbimo** [comment]
@uwe-koeckemann Could handle the small todo above ?

**Comment by uwe-koeckemann** [comment]
> @uwe-koeckemann Could you handle the small todo above ?

Done!

**Comment by arbimo** [comment]
Perfect, thanks!

**Pull request merged**
